name: plado
description: "Planner TODO"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Database
  sqflite: ^2.3.3+1

  # System
  path: ^1.9.0
  intl: ^0.19.0
  timezone: ^0.9.4
  flutter_local_notifications: ^17.2.2
  timeago: ^3.7.0
  wakelock_plus: ^1.2.8
  url_launcher: ^6.3.0
  share_plus: ^10.0.2
  file_picker: ^8.1.2
  permission_handler: ^11.3.1

  # State management
  provider: ^6.1.2
  percent_indicator: ^4.2.3

  # UI
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/icons/

  fonts:
    - family: 'Raleway'
      fonts:
        - asset: assets/fonts/raleway_regular.ttf
    - family: 'Roboto Slab'
      fonts:
        - asset: assets/fonts/roboto_slab_light.ttf