name: plado
description: "Planner TODO"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Database
  sqflite: ^2.3.3+1

  # System
  path: ^1.9.0
  intl: ^0.19.0
  timezone: ^0.9.3
  flutter_local_notifications: ^17.2.1

  # State management
  provider: ^6.1.2

  # UI
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: 'Raleway'
      fonts:
        - asset: assets/fonts/raleway_regular.ttf